# Generated by Django 5.1.1 on 2024-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.IntegerField(default=7),
        ),
    ]
