# Generated by Django 5.1.1 on 2024-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0005_sizes_remove_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.IntegerField(default=7),
        ),
    ]
