# Generated by Django 5.1.1 on 2024-09-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0006_alter_sizes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='z_footware_app.sizes'),
        ),
    ]
