# Generated by Django 5.1.1 on 2024-09-20 05:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0013_alter_product_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 20, 11, 6, 4, 176640))),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_footware_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_footware_app.register')),
            ],
        ),
    ]
