# Generated by Django 5.1.1 on 2024-09-20 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0014_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 23, 41, 347625)),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
