# Generated by Django 5.1.1 on 2024-09-20 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0015_alter_customer_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 20, 12, 31, 20, 11074)),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
