# Generated by Django 5.1.1 on 2024-09-26 10:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_footware_app', '0016_alter_customer_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 15, 59, 44, 115603)),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='z_footware_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_footware_app.register')),
            ],
        ),
    ]
